auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: 行云流水's Blog
url: http://xylsh.github.com
feed: /atom.xml
author_info: <a href="http://xylsh.github.com/">行云流水</a>
